services:
  caddy:
    image: caddy:2.11.2
    depends_on:
      - jenkins
      - nexus
      - registry
      - registry-ui
    environment:
      - CADDY_DOMAIN=${CADDY_DOMAIN}
      - CADDY_TLS_MODE=${CADDY_TLS_MODE}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./caddy:/etc/caddy
      - ${CICD_VOLUME_DIR}/caddy/data:/data
      - ${CICD_VOLUME_DIR}/caddy/config:/config

  jenkins:
    build:
      context: ./
      dockerfile: jenkins.Dockerfile
    environment:
      - JAVA_OPTS="-Dmail.smtp.starttls.enable=true -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CICD_VOLUME_DIR}/jenkins_home:/var/jenkins_home
    restart: unless-stopped

  nexus:
    image: sonatype/nexus3:3.91.1
    volumes:
      - ${CICD_VOLUME_DIR}/nexus-data:/nexus-data

  registry:
    image: registry:3.1.1
    environment:
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: '[http://localhost]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,OPTIONS,DELETE]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
    volumes:
      - ${CICD_VOLUME_DIR}/docker-registry:/var/lib/registry
      - ./registry-config.yml:/etc/docker/registry/config.yml

  registry-ui:
    image: joxit/docker-registry-ui:2.6.0
    environment:
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=false
      - THEME=dark
    depends_on:
      - registry
