version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: false
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['*']
    Access-Control-Max-Age: [1728000]
